//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.21 at 02:02:59 PM EDT 
//


package com.revature.models;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for superPower.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="superPower">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SuperStrength"/>
 *     &lt;enumeration value="Invisibility"/>
 *     &lt;enumeration value="Flight"/>
 *     &lt;enumeration value="MindReader"/>
 *     &lt;enumeration value="Telekinesis"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "superPower")
@XmlEnum
public enum SuperPower {

    @XmlEnumValue("SuperStrength")
    SUPER_STRENGTH("SuperStrength"),
    @XmlEnumValue("Invisibility")
    INVISIBILITY("Invisibility"),
    @XmlEnumValue("Flight")
    FLIGHT("Flight"),
    @XmlEnumValue("MindReader")
    MIND_READER("MindReader"),
    @XmlEnumValue("Telekinesis")
    TELEKINESIS("Telekinesis");
    private final String value;

    SuperPower(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SuperPower fromValue(String v) {
        for (SuperPower c: SuperPower.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
